import { TravelPackage } from '@/types';

export const staticPackages: TravelPackage[] = [
  // ─── FESTIVAL TRIPS ──────────────────────────────────────
  {
    id: 'theyyam-unseen-kannur',
    title: 'Theyyam + Unseen Kannur, Trekking & Lily Boating',
    slug: 'theyyam-unseen-kannur',
    category: 'Festival',
    duration: '2D 1N',
    price: 5999,
    location: 'Kannur, Kerala',
    description: 'Witness the mystical overnight Theyyam ritual art form at Kannur with coastal sightseeing and drive-in beach experiences.',
    longDescription: 'Immerse yourself in the ancient Theyyam ritual at Purakkatt Vettakkorumakan Kshetram — a divine art form that transforms performers into living gods from 7pm to 11am. Beyond the ritual, explore Kannur\'s untouched coastline including the famous Muzhappilangad drive-in beach, the dramatic cliff walks of Payyambalam, and the serene Dharmadam island accessible only at low tide. This trip captures the mystical soul of North Kerala.',
    highlights: ['Overnight Theyyam ritual experience (7pm-11am)', 'Muzhappilangad drive-in beach', 'Payyambalam beach cliff walk', 'Dharmadam beach & island visit'],
    inclusions: ['3-star accommodation', 'Breakfast', 'Airport pickup/drop', 'Private cab for sightseeing', 'Theyyam temple visit arrangements'],
    exclusions: ['Lunch & dinner', 'Personal expenses', 'Travel insurance', 'Flight/train tickets'],
    itinerary: [
      { day: 1, title: 'Arrival & Kannur Coastal Tour', description: 'Arrive at Kannur and check into hotel. After freshening up, head out to explore the stunning coastline.', activities: ['Visit Payyambalam Beach & cliff walk', 'Drive on Muzhappilangad drive-in beach', 'Explore Dharmadam beach & island', 'Evening: Head to Theyyam temple venue'], meals: ['Dinner (own)'], accommodation: '3-star hotel in Kannur' },
      { day: 2, title: 'Theyyam Ritual & Departure', description: 'Witness the overnight Theyyam performance — an unforgettable spiritual experience. The ritual runs from 7pm to early morning.', activities: ['Overnight Theyyam ritual (7pm - 11am)', 'Photography & cultural interaction', 'Breakfast and checkout', 'Transfer to airport/station'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/theyyam-kerala.jpg',
      '/images/packages/kerala-backwaters.jpg',
      '/images/packages/india-temple.jpg',
      '/images/packages/kashmir-dal-lake.jpg',
    ],
    thumbnailImage: '/images/packages/theyyam-kerala.jpg',
    maxGroupSize: 15,
    difficulty: 'Easy',
    isActive: true,
    isFeatured: true,
    tags: ['festival', 'cultural', 'theyyam', 'kerala'],
    pdfUrl: '/pdfs/theyyam-unseen-kannur.pdf',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'rann-utsav-4d3n',
    title: 'Rann Utsav Festival Retreat — 4D 3N',
    slug: 'rann-utsav-4d3n',
    category: 'Festival',
    duration: '4D 3N',
    price: 15000,
    location: 'Rann of Kutch, Gujarat',
    description: 'Experience the magical white desert at Rann Utsav Tent City with cultural performances, camel rides, and Kutch heritage tours.',
    longDescription: 'Stay in luxury tents at Dhordo Tent City and witness the vast white salt desert stretching endlessly under the full moon. This 4-day retreat takes you through the best of Kutch — from the colourful handicraft villages and the historic Vijay Vilas Palace at Mandvi Beach to the breathtaking views from Kala Dungar. Evenings come alive with folk music, dance, and traditional Kutchi cuisine.',
    highlights: ['White Rann sunset & sunrise walk', 'Mandvi private beach & Vijay Vilas Palace', 'Kala Dungar — highest peak of Kutch', 'Traditional Kutchi cultural performances'],
    inclusions: ['Tent city accommodation (3 nights)', 'All meals (breakfast, lunch, dinner)', 'Airport/station pickup & drop', 'AC transport for sightseeing', 'Cultural show passes', 'Camel cart / bus ride to White Rann'],
    exclusions: ['Flight/train tickets', 'Personal expenses', 'Camera charges at monuments', 'Travel insurance', 'Items not mentioned in inclusions'],
    itinerary: [
      { day: 1, title: 'Arrival at Bhuj & Kutch Heritage', description: 'Arrive at Bhuj and transfer to Tent City at Dhordo. Settle into your luxury tent and explore the surroundings.', activities: ['Airport/station pickup at Bhuj', 'Transfer to Dhordo Tent City', 'Check-in & welcome drinks', 'Evening: White Rann sunset walk', 'Night: Cultural folk performances'], meals: ['Dinner'], accommodation: 'Tent City Dhordo' },
      { day: 2, title: 'White Rann & Kala Dungar', description: 'Wake up early for a magical sunrise over the white salt desert, then explore the highest peak of Kutch.', activities: ['Sunrise at White Rann', 'Breakfast at tent city', 'Visit Kala Dungar (Black Hill viewpoint)', 'Explore Hodka village handicrafts', 'Evening: Rann under moonlight'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Tent City Dhordo' },
      { day: 3, title: 'Mandvi Beach & Vijay Vilas Palace', description: 'Explore the royal heritage of Kutch at Mandvi with its private beach and the stunning Vijay Vilas Palace.', activities: ['Drive to Mandvi (90 km)', 'Vijay Vilas Palace tour', 'Mandvi private beach & windmills', 'Visit Skyzilla adventure zone', 'Farewell dinner with live music'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Tent City Dhordo' },
      { day: 4, title: 'Departure', description: 'After breakfast, checkout and transfer to Bhuj airport/station with beautiful memories of the white desert.', activities: ['Breakfast & checkout', 'Last minute shopping at Bhuj', 'Transfer to Bhuj airport/station'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/rann-of-kutch.jpg',
      '/images/packages/kerala-backwaters.jpg',
      '/images/packages/munnar-tea.jpg',
      '/images/packages/andaman-beach.jpg',
    ],
    thumbnailImage: '/images/packages/rann-of-kutch.jpg',
    maxGroupSize: 20,
    difficulty: 'Easy',
    isActive: true,
    isFeatured: true,
    tags: ['festival', 'desert', 'gujarat', 'cultural'],
    pdfUrl: '/pdfs/rann-utsav-4d3n.pdf',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'rann-utsav-3d2n',
    title: 'Rann Utsav Short Retreat — 3D 2N',
    slug: 'rann-utsav-3d2n',
    category: 'Festival',
    duration: '3D 2N',
    price: 12000,
    location: 'Rann of Kutch, Gujarat',
    description: 'A compact white desert experience with Rann Utsav tent city stay, cultural performances, and Kutch sightseeing.',
    longDescription: 'A shorter version of the Rann Utsav experience perfect for long weekends. Stay at the iconic tent city, walk on the infinite white salt desert at sunset, enjoy Kutchi folk performances under the stars, and visit the heritage sites of Kutch — all packed into 3 memorable days.',
    highlights: ['White Rann desert sunset walk', 'Tent city luxury stay', 'Cultural folk performances', 'Kutch heritage tour'],
    inclusions: ['Tent city accommodation (2 nights)', 'All meals', 'AC transport', 'Cultural show passes', 'Rann entry permits'],
    exclusions: ['Flight/train tickets', 'Personal expenses', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrival & White Rann Sunset', description: 'Arrive at Bhuj, transfer to Dhordo Tent City. Experience the magical White Rann at sunset.', activities: ['Bhuj pickup & transfer to Dhordo', 'Check-in at Tent City', 'White Rann sunset walk', 'Cultural performances & dinner'], meals: ['Dinner'], accommodation: 'Tent City Dhordo' },
      { day: 2, title: 'Kutch Exploration', description: 'Full day exploring the heritage and natural beauty of the Kutch region.', activities: ['Sunrise at White Rann', 'Kala Dungar viewpoint', 'Local handicraft villages', 'Evening folk music & stargazing'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Tent City Dhordo' },
      { day: 3, title: 'Departure', description: 'Breakfast and checkout with transfer back to Bhuj.', activities: ['Breakfast & checkout', 'Bhuj local market', 'Transfer to airport/station'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/rann-of-kutch.jpg',
      '/images/packages/andaman-beach.jpg',
      '/images/packages/kerala-backwaters.jpg',
    ],
    thumbnailImage: '/images/packages/rann-of-kutch.jpg',
    maxGroupSize: 20,
    difficulty: 'Easy',
    isActive: true,
    isFeatured: false,
    tags: ['festival', 'desert', 'gujarat'],
    pdfUrl: '/pdfs/rann-utsav-3d2n.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'rann-utsav-2d1n',
    title: 'Rann Utsav Express — 2D 1N',
    slug: 'rann-utsav-2d1n',
    category: 'Festival',
    duration: '2D 1N',
    price: 8000,
    location: 'Rann of Kutch, Gujarat',
    description: 'A quick weekend getaway to the white desert with one night tent city stay and Rann sunrise experience.',
    longDescription: 'The perfect weekend escape to the White Rann. Arrive, settle into your tent, walk the endless white salt desert at sunset, enjoy an evening of folk music, and wake up to a stunning desert sunrise before heading back. Short, sweet, and unforgettable.',
    highlights: ['White Rann sunrise & sunset', 'One night tent city stay', 'Cultural folk show', 'Desert walk experience'],
    inclusions: ['Tent city accommodation (1 night)', 'Dinner & breakfast', 'AC transport from Bhuj', 'Rann entry permits'],
    exclusions: ['Flight/train tickets', 'Lunch', 'Personal expenses'],
    itinerary: [
      { day: 1, title: 'Arrival & White Rann Sunset', description: 'Arrive at Bhuj and transfer to Dhordo. Walk the White Rann at sunset and enjoy cultural evening.', activities: ['Bhuj pickup', 'Transfer to Tent City', 'White Rann sunset walk', 'Folk dance & music show', 'Dinner under the stars'], meals: ['Dinner'], accommodation: 'Tent City Dhordo' },
      { day: 2, title: 'Sunrise & Departure', description: 'Catch the magical White Rann sunrise, have breakfast, and head back.', activities: ['Early morning Rann sunrise', 'Breakfast at tent city', 'Checkout & departure to Bhuj'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/rann-of-kutch.jpg',
      '/images/packages/munnar-tea.jpg',
    ],
    thumbnailImage: '/images/packages/rann-of-kutch.jpg',
    maxGroupSize: 20,
    difficulty: 'Easy',
    isActive: true,
    isFeatured: false,
    tags: ['festival', 'desert', 'weekend'],
    pdfUrl: '/pdfs/rann-utsav-2d1n.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'malarikkal-lily-festival',
    title: 'Malarikkal Lily Festival — Kerala Backwaters',
    slug: 'malarikkal-lily-festival',
    category: 'Festival',
    duration: '2D 1N',
    price: 2999,
    location: 'Malarikkal & Kochi, Kerala',
    description: 'Boat through a pink heaven of lotus blooms at Malarikkal, combined with Kochi heritage sightseeing and Kerala backwaters.',
    longDescription: 'Every year from July to October, the waters of Malarikkal transform into a breathtaking carpet of pink lotus blooms. Glide through this living painting on a traditional boat, then explore Kochi\'s rich Portuguese and Dutch heritage — Fort Kochi, the Chinese fishing nets, Santa Cruz Basilica, and India\'s first water metro. Finish with a serene Kumarakom backwater cruise.',
    highlights: ['Lotus bloom boating at Malarikkal', 'India\'s first water metro ride', 'Kumarakom houseboat cruise', 'Kochi heritage walk & Chinese fishing nets'],
    inclusions: ['Accommodation (1 night)', 'Breakfast', 'All boating charges', 'AC transport', 'Water metro tickets', 'Local guide'],
    exclusions: ['Lunch & dinner', 'Personal expenses', 'Travel insurance', 'Flight/train tickets'],
    itinerary: [
      { day: 1, title: 'Kochi Heritage & Malarikkal Lily Boating', description: 'Start with Kochi sightseeing, then head to Malarikkal for the magical lotus boating experience.', activities: ['Fort Kochi & Chinese fishing nets', 'Santa Cruz Basilica & Dutch Palace', 'India\'s first water metro ride', 'Malarikkal lily (lotus) boating', 'Check-in at hotel'], meals: ['Dinner (own)'], accommodation: 'Hotel in Kumarakom/Kochi' },
      { day: 2, title: 'Kumarakom Backwaters & Departure', description: 'Enjoy a peaceful morning backwater cruise before heading back.', activities: ['Breakfast at hotel', 'Kumarakom backwater houseboat cruise', 'Bird sanctuary visit (optional)', 'Transfer to Kochi airport/station'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/kerala-backwaters.jpg',
      '/images/packages/kerala-backwaters.jpg',
      '/images/packages/kashmir-dal-lake.jpg',
    ],
    thumbnailImage: '/images/packages/kerala-backwaters.jpg',
    maxGroupSize: 15,
    difficulty: 'Easy',
    isActive: true,
    isFeatured: true,
    tags: ['festival', 'kerala', 'backwaters', 'nature'],
    pdfUrl: '/pdfs/malarikkal-lily-festival.pdf',
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ─── TREKS ───────────────────────────────────────────────
  {
    id: 'everest-base-camp-trek',
    title: 'Everest Base Camp Trek — Nepal',
    slug: 'everest-base-camp-trek',
    category: 'Trek',
    duration: '14D 13N',
    price: 45000,
    location: 'Everest Region, Nepal',
    description: 'The iconic trek to the base of the world\'s highest mountain through Sherpa villages and ancient monasteries.',
    longDescription: 'Stand at the foot of Mount Everest on this legendary 14-day trek through the Khumbu region. Starting from Lukla, wind through rhododendron forests, cross suspension bridges over roaring rivers, and pass through iconic Sherpa villages like Namche Bazaar and Dingboche. Visit the ancient Tengboche Monastery with panoramic Himalayan views. Reach Everest Base Camp at 5,364m and climb Kala Patthar for the ultimate sunrise over Everest.',
    highlights: ['Everest Base Camp (5,364m)', 'Kala Patthar sunrise viewpoint', 'Namche Bazaar — gateway to Everest', 'Tengboche Monastery visit'],
    inclusions: ['Airport transfers in Kathmandu', 'Domestic flights (Kathmandu-Lukla-Kathmandu)', 'All lodge accommodations during trek', 'All meals during trek (breakfast, lunch, dinner)', 'Experienced English-speaking guide', 'Porter service (1 porter per 2 trekkers)', 'TIMS permit & National Park fees', 'First aid medical kit'],
    exclusions: ['International flights', 'Nepal visa fees', 'Travel insurance (mandatory)', 'Personal trekking gear', 'Hot showers & charging at lodges', 'Tips for guide & porters', 'Emergency evacuation costs'],
    itinerary: [
      { day: 1, title: 'Arrival in Kathmandu', description: 'Arrive at Tribhuvan International Airport. Transfer to hotel and attend trek briefing.', activities: ['Airport pickup', 'Hotel check-in at Thamel', 'Trek briefing & gear check', 'Welcome dinner'], meals: ['Dinner'], accommodation: 'Hotel in Kathmandu' },
      { day: 2, title: 'Fly to Lukla & Trek to Phakding', description: 'Scenic 35-minute mountain flight to Lukla (2,840m). Begin trekking through pine forests to Phakding.', activities: ['Fly Kathmandu to Lukla', 'Trek begins: Lukla to Phakding (3-4 hrs)', 'Cross suspension bridges', 'Acclimatization walk'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Phakding' },
      { day: 3, title: 'Trek to Namche Bazaar', description: 'Trek along the Dudh Kosi river valley to the legendary Namche Bazaar (3,440m) — the Sherpa capital.', activities: ['Trek Phakding to Namche (5-6 hrs)', 'Enter Sagarmatha National Park', 'First Everest viewpoint', 'Explore Namche market'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Namche Bazaar' },
      { day: 4, title: 'Acclimatization Day in Namche', description: 'Essential rest day for altitude acclimatization with optional hikes to Everest View Hotel and Khumjung village.', activities: ['Hike to Everest View Hotel (3,880m)', 'Visit Khumjung village & school', 'Explore Namche museum', 'Rest and hydrate'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Namche Bazaar' },
      { day: 5, title: 'Trek to Tengboche', description: 'Trek through forests with stunning views to Tengboche (3,867m) — home to the famous monastery.', activities: ['Trek Namche to Tengboche (5-6 hrs)', 'Visit Tengboche Monastery', 'Panoramic views of Everest, Lhotse, Ama Dablam'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Tengboche' },
      { day: 6, title: 'Trek to Dingboche', description: 'Descend through forest, cross rivers, and climb to Dingboche (4,410m) in the Imja Valley.', activities: ['Trek Tengboche to Dingboche (5-6 hrs)', 'Cross Imja River', 'Views of Island Peak & Lhotse wall'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Dingboche' },
      { day: 7, title: 'Acclimatization Day in Dingboche', description: 'Another critical acclimatization day with a hike to Nagarjun Hill for 360-degree views.', activities: ['Hike to Nagarjun Hill (5,100m)', 'Views of Makalu, Lhotse, Chalitse', 'Rest and prepare for higher altitude'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Dingboche' },
      { day: 8, title: 'Trek to Lobuche', description: 'Trek past the Thukla memorial (stone cairns honoring fallen climbers) to Lobuche (4,940m).', activities: ['Trek Dingboche to Lobuche (5-6 hrs)', 'Thukla Pass memorial', 'Views of Pumori & Nuptse'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Lobuche' },
      { day: 9, title: 'Trek to Gorak Shep & Everest Base Camp', description: 'The big day! Trek to Gorak Shep, drop bags, then hike to Everest Base Camp (5,364m).', activities: ['Trek Lobuche to Gorak Shep (3 hrs)', 'Hike to Everest Base Camp (3 hrs)', 'Celebrate at Base Camp!', 'Return to Gorak Shep'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Gorak Shep' },
      { day: 10, title: 'Kala Patthar Sunrise & Trek to Pheriche', description: 'Pre-dawn hike to Kala Patthar (5,545m) for the ultimate Everest sunrise. Then descend to Pheriche.', activities: ['4am start — hike to Kala Patthar', 'Sunrise over Everest panorama', 'Descend to Pheriche (4-5 hrs)'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Pheriche' },
      { day: 11, title: 'Trek to Namche Bazaar', description: 'Retrace the route downhill through Tengboche back to Namche Bazaar.', activities: ['Trek Pheriche to Namche (6-7 hrs)', 'Final views of Everest region', 'Celebrate trek completion'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Namche' },
      { day: 12, title: 'Trek to Lukla', description: 'Final day of trekking back to Lukla with farewell dinner.', activities: ['Trek Namche to Lukla (6-7 hrs)', 'Farewell dinner with guide & porters'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Lukla' },
      { day: 13, title: 'Fly to Kathmandu', description: 'Morning flight from Lukla to Kathmandu. Free afternoon for shopping and sightseeing.', activities: ['Fly Lukla to Kathmandu', 'Free time — Thamel shopping', 'Optional: Pashupatinath / Boudhanath visit'], meals: ['Breakfast'], accommodation: 'Hotel in Kathmandu' },
      { day: 14, title: 'Departure', description: 'Transfer to airport for your flight home.', activities: ['Breakfast & checkout', 'Airport transfer', 'Departure'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/everest-nepal.jpg',
      '/images/packages/nepal-mountains-2.jpg',
      '/images/packages/nepal-village.jpg',
      '/images/packages/everest-nepal.jpg',
      '/images/packages/everest-nepal.jpg',
    ],
    thumbnailImage: '/images/packages/everest-nepal.jpg',
    maxGroupSize: 12,
    difficulty: 'Challenging',
    isActive: true,
    isFeatured: true,
    tags: ['trek', 'nepal', 'everest', 'iconic'],
    pdfUrl: '/pdfs/everest-base-camp-trek.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ghorepani-poonhill-trek',
    title: 'Ghorepani & Poon Hill Trek — Nepal',
    slug: 'ghorepani-poonhill-trek',
    category: 'Trek',
    duration: '5D 4N',
    price: 18000,
    location: 'Annapurna Region, Nepal',
    description: 'A beginner-friendly trek with breathtaking sunrise views of the Annapurna and Dhaulagiri ranges from Poon Hill.',
    longDescription: 'Perfect for first-time trekkers, this 5-day adventure takes you through lush rhododendron forests, terraced rice fields, and charming Gurung villages to Poon Hill (3,210m). Wake before dawn for a panoramic sunrise that lights up the Annapurna and Dhaulagiri ranges in golden hues — one of Nepal\'s most photographed moments.',
    highlights: ['Poon Hill sunrise (3,210m)', 'Annapurna & Dhaulagiri panorama', 'Gurung village homestays', 'Rhododendron forests'],
    inclusions: ['All lodge accommodations', 'All meals during trek', 'English-speaking guide', 'Porter service', 'TIMS & ACAP permits', 'Pokhara transfers'],
    exclusions: ['International/domestic flights', 'Travel insurance', 'Personal gear', 'Hot showers at lodges', 'Tips'],
    itinerary: [
      { day: 1, title: 'Drive to Nayapul & Trek to Tikhedhunga', description: 'Drive from Pokhara to Nayapul, then begin trekking through villages and rice terraces.', activities: ['Drive Pokhara to Nayapul (1.5 hrs)', 'Trek to Tikhedhunga (4-5 hrs)', 'Pass through Birethanti village'], meals: ['Lunch', 'Dinner'], accommodation: 'Lodge in Tikhedhunga' },
      { day: 2, title: 'Trek to Ghorepani', description: 'A steady climb through beautiful forests, stone staircases, and Magar villages.', activities: ['Trek Tikhedhunga to Ghorepani (5-6 hrs)', 'Climb 3,300 stone steps to Ulleri', 'Walk through rhododendron & oak forests'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Ghorepani' },
      { day: 3, title: 'Poon Hill Sunrise & Trek to Tadapani', description: 'The highlight — pre-dawn hike to Poon Hill for a legendary Himalayan sunrise.', activities: ['4:30am hike to Poon Hill (1 hr)', 'Sunrise over Annapurna & Dhaulagiri', '360-degree mountain panorama', 'Trek to Tadapani (4-5 hrs)'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Tadapani' },
      { day: 4, title: 'Trek to Ghandruk', description: 'Descend through forests to the beautiful Gurung village of Ghandruk with Annapurna views.', activities: ['Trek Tadapani to Ghandruk (3-4 hrs)', 'Visit Gurung museum', 'Explore traditional stone village', 'Views of Annapurna South & Machapuchare'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Lodge in Ghandruk' },
      { day: 5, title: 'Trek to Nayapul & Drive to Pokhara', description: 'Final descent to Nayapul and drive back to Pokhara.', activities: ['Trek Ghandruk to Nayapul (4-5 hrs)', 'Drive to Pokhara', 'Free time at Lakeside'], meals: ['Breakfast', 'Lunch'], accommodation: '' },
    ],
    images: [
      '/images/packages/everest-nepal.jpg',
      '/images/packages/nepal-mountains-2.jpg',
      '/images/packages/nepal-village.jpg',
    ],
    thumbnailImage: '/images/packages/everest-nepal.jpg',
    maxGroupSize: 15,
    difficulty: 'Easy',
    isActive: true,
    isFeatured: true,
    tags: ['trek', 'nepal', 'beginner', 'sunrise'],
    pdfUrl: '/pdfs/ghorepani-poonhill-trek.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  ...[
    { id: 'mount-manaslu-trek', title: 'Mount Manaslu Trek — Nepal', dur: '14D 13N', price: 45000, loc: 'Manaslu, Nepal', desc: 'Trek around the 8th highest mountain in the world through remote villages, ancient monasteries, and the Larkya La Pass at 5,160m.', diff: 'Challenging' as const, hi: ['Larkya La Pass (5,160m)', 'Remote Tibetan villages', 'Ancient Buddhist monasteries', 'Manaslu Conservation Area'], pdf: '/pdfs/mount-manaslu-trek.jpg' },
    { id: 'mardi-himal-trek', title: 'Mardi Himal Trek — Nepal', dur: '7D 6N', price: 25000, loc: 'Mardi Himal, Nepal', desc: 'A hidden gem trek offering stunning views of Annapurna and Machapuchare through rhododendron forests.', diff: 'Moderate' as const, hi: ['Panoramic Annapurna views', 'Machapuchare close-up', 'Rhododendron forest trails', 'Less crowded alternative'], pdf: '/pdfs/mardi-himal-trek.jpg' },
    { id: 'kanchenjunga-base-camp-trek', title: 'Kanchenjunga Base Camp Trek — Nepal', dur: '18D 17N', price: 65000, loc: 'Kanchenjunga, Nepal', desc: 'Trek to the base of the world\'s 3rd highest peak through pristine wilderness and remote Limbu villages.', diff: 'Challenging' as const, hi: ['Base camp of 3rd highest peak', 'Pristine remote wilderness', 'Limbu tribal villages', 'Glacial moraines & high passes'], pdf: '/pdfs/kanchenjunga-base-camp-trek.jpg' },
    { id: 'gokyo-everest-base-camp-trek', title: 'Gokyo + Everest Base Camp Trek — Nepal', dur: '16D 15N', price: 55000, loc: 'Everest Region, Nepal', desc: 'The ultimate Everest experience combining Gokyo Lakes, Cho La Pass, and Everest Base Camp.', diff: 'Challenging' as const, hi: ['Gokyo Ri panoramic views', 'Cho La Pass crossing', 'Everest Base Camp', 'Turquoise Gokyo Lakes'], pdf: '/pdfs/gokyo-everest-base-camp-trek.jpg' },
    { id: 'everest-three-high-passes', title: 'Everest Three High Passes Trek — Nepal', dur: '18D 17N', price: 60000, loc: 'Everest Region, Nepal', desc: 'The most challenging Everest trek crossing Kongma La, Cho La, and Renjo La — all above 5,000m.', diff: 'Challenging' as const, hi: ['Three passes above 5,000m', 'Kongma La, Cho La & Renjo La', 'Gokyo Lakes', 'Everest Base Camp'], pdf: '/pdfs/everest-three-high-passes.jpg' },
    { id: 'annapurna-circuit-trek', title: 'Annapurna Circuit Trek — Nepal', dur: '14D 13N', price: 42000, loc: 'Annapurna Region, Nepal', desc: 'The classic circuit around the Annapurna massif crossing the Thorong La Pass at 5,416m.', diff: 'Challenging' as const, hi: ['Thorong La Pass (5,416m)', 'Diverse terrain & climate zones', 'Muktinath Temple', 'Manang Valley'], pdf: '/pdfs/annapurna-circuit-trek.jpg' },
    { id: 'annapurna-base-camp-trek', title: 'Annapurna Base Camp Trek — Nepal', dur: '10D 9N', price: 32000, loc: 'Annapurna Region, Nepal', desc: 'Trek into the heart of the Annapurna sanctuary surrounded by towering peaks and bamboo forests.', diff: 'Moderate' as const, hi: ['Annapurna Base Camp (4,130m)', 'Machapuchare Base Camp', 'Natural hot springs at Jhinu', 'Bamboo & rhododendron forests'], pdf: '/pdfs/annapurna-base-camp-trek.jpg' },
  ].map(t => ({
    id: t.id, title: t.title, slug: t.id, category: 'Trek' as const, duration: t.dur, price: t.price, location: t.loc,
    description: t.desc,
    longDescription: `${t.desc} This trek is organized by GP Travels with experienced guides, all permits, lodge accommodations, and full meal plans. Contact us for detailed day-by-day itinerary and customized group pricing.`,
    highlights: t.hi,
    inclusions: ['All lodge accommodations', 'All meals during trek', 'Experienced English-speaking guide', 'Porter service', 'All permits & national park fees', 'Airport transfers', 'First aid kit'],
    exclusions: ['International/domestic flights', 'Nepal visa fees', 'Travel insurance (mandatory)', 'Personal trekking gear', 'Hot showers & charging', 'Tips for guide & porters'],
    itinerary: [
      { day: 1, title: 'Arrival & Briefing', description: 'Arrive in Kathmandu/Pokhara. Hotel check-in, trek briefing, and gear check.', activities: ['Airport pickup', 'Hotel check-in', 'Trek briefing & documentation', 'Welcome dinner'], meals: ['Dinner'], accommodation: 'Hotel' },
      { day: 2, title: 'Trek Begins', description: 'Start the trek from the trailhead. Walk through villages and forests as the adventure begins.', activities: ['Transfer to trailhead', 'Begin trekking', 'Pass through local villages', 'Settle at first lodge'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Trekking lodge' },
      { day: 3, title: 'Into the Mountains', description: 'Continue ascending through changing landscapes. The views get more dramatic with each step.', activities: ['Morning trek through forests', 'Cross rivers & suspension bridges', 'Reach higher elevation camp'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Trekking lodge' },
    ],
    images: [
      '/images/packages/everest-nepal.jpg',
      '/images/packages/nepal-mountains-2.jpg',
      '/images/packages/nepal-village.jpg',
    ],
    thumbnailImage: '/images/packages/everest-nepal.jpg',
    maxGroupSize: 12, difficulty: t.diff, isActive: true, isFeatured: false,
    tags: ['trek', 'nepal', 'himalaya'], pdfUrl: t.pdf,
    createdAt: new Date(), updatedAt: new Date(),
  } as TravelPackage)),

  // ─── FAMILY / INTERNATIONAL ──────────────────────────────
  ...[
    { id: 'south-korea-8d7n', title: 'South Korea Explorer — 8D 7N', dur: '8D 7N', price: 85000, loc: 'Seoul & Busan, South Korea', cat: 'Workation' as const, desc: 'A comprehensive South Korea experience covering Seoul, Busan, K-pop culture, temples, and street food.', hi: ['Gyeongbokgung Palace tour', 'Busan beaches & Gamcheon Village', 'K-pop cultural experiences', 'Korean street food trails'], img: '/images/packages/seoul-palace.jpg', pdf: '/pdfs/south-korea-8d7n.jpg' },
    { id: 'south-korea-6d5n', title: 'South Korea Highlights — 6D 5N', dur: '6D 5N', price: 65000, loc: 'Seoul, South Korea', cat: 'Workation' as const, desc: 'Discover the best of Seoul with palaces, K-pop culture, Namsan Tower, and authentic Korean dining.', hi: ['Gyeongbokgung Palace & Hanbok', 'Namsan Tower & Myeongdong', 'DMZ tour', 'Korean BBQ & street food'], img: '/images/packages/seoul-palace.jpg', pdf: '/pdfs/south-korea-6d5n.jpg' },
    { id: 'south-korea-4d3n', title: 'South Korea Quick Escape — 4D 3N', dur: '4D 3N', price: 48000, loc: 'Seoul, South Korea', cat: 'Workation' as const, desc: 'A quick Seoul getaway — palaces, shopping districts, and K-food culture in 4 days.', hi: ['Seoul palace tour', 'Myeongdong & Insadong', 'K-food experiences', 'Namsan Tower views'], img: '/images/packages/seoul-palace.jpg', pdf: '/pdfs/south-korea-4d3n.jpg' },
  ].map(t => ({
    id: t.id, title: t.title, slug: t.id, category: t.cat, duration: t.dur, price: t.price, location: t.loc,
    description: t.desc,
    longDescription: `${t.desc} GP Travels curates every detail of this international experience — from visa assistance and comfortable stays to local guides and authentic dining. Contact us for group pricing and custom itineraries.`,
    highlights: t.hi,
    inclusions: ['Hotel accommodation', 'Daily breakfast', 'Airport transfers', 'AC transport for sightseeing', 'English-speaking local guide', 'All entry tickets mentioned'],
    exclusions: ['International flights', 'Visa fees', 'Lunch & dinner', 'Personal shopping', 'Travel insurance', 'Tips'],
    itinerary: [
      { day: 1, title: 'Arrival & City Introduction', description: 'Arrive at the destination, hotel check-in, and explore the neighbourhood.', activities: ['Airport pickup & hotel transfer', 'Neighbourhood orientation walk', 'Welcome dinner (own expense)'], meals: ['Breakfast (if arrival is early)'], accommodation: 'Hotel' },
      { day: 2, title: 'Heritage & Culture Day', description: 'Full day exploring the iconic cultural landmarks and historical sites.', activities: ['Palace/temple visits', 'Museum & heritage sites', 'Local market exploration', 'Traditional cuisine tasting'], meals: ['Breakfast'], accommodation: 'Hotel' },
      { day: 3, title: 'Adventure & Local Life', description: 'Experience the adventurous and modern side of the destination.', activities: ['Adventure activity / day trip', 'Shopping district visit', 'Street food trail', 'Evening entertainment'], meals: ['Breakfast'], accommodation: 'Hotel' },
    ],
    images: [t.img, '/images/packages/seoul-palace.jpg', '/images/packages/bangkok-grand-palace.jpg'],
    thumbnailImage: t.img, maxGroupSize: 15, difficulty: 'Easy' as const, isActive: true, isFeatured: false,
    tags: ['international'], pdfUrl: t.pdf, createdAt: new Date(), updatedAt: new Date(),
  } as TravelPackage)),

  // ─── ADVENTURE ───────────────────────────────────────────
  {
    id: 'thailand-5d4n',
    title: 'Thailand Adventure — 5D 4N',
    slug: 'thailand-5d4n',
    category: 'Adventure',
    duration: '5D 4N',
    price: 28000,
    location: 'Bangkok & Pattaya, Thailand',
    description: 'Explore the vibrant streets of Bangkok and the beaches of Pattaya with temples, floating markets, and island hopping.',
    longDescription: 'Thailand awaits with its intoxicating blend of ancient temples, bustling markets, and tropical beaches. Explore the Grand Palace and Wat Pho in Bangkok, haggle at the floating markets, then escape to Pattaya\'s Coral Island for crystal-clear waters and water sports. Evenings come alive with Thai street food, rooftop bars, and the famous night markets.',
    highlights: ['Grand Palace & Wat Pho', 'Floating market experience', 'Pattaya beach & Coral Island', 'Thai street food tour'],
    inclusions: ['4-star hotel accommodation', 'Daily breakfast', 'Airport transfers', 'AC transport', 'Coral Island speedboat', 'City tour with guide'],
    exclusions: ['International flights', 'Visa on arrival fee', 'Lunch & dinner', 'Water sports at Coral Island', 'Personal expenses', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrival in Bangkok', description: 'Arrive at Suvarnabhumi Airport, transfer to hotel, and explore nearby markets.', activities: ['Airport pickup', 'Hotel check-in', 'Evening: Khao San Road / Asiatique night market'], meals: [], accommodation: '4-star hotel in Bangkok' },
      { day: 2, title: 'Bangkok Temple & Culture Tour', description: 'Full day exploring Bangkok\'s magnificent temples and cultural landmarks.', activities: ['Grand Palace & Emerald Buddha', 'Wat Pho (Reclining Buddha)', 'Chao Phraya river boat ride', 'Evening: Chinatown street food'], meals: ['Breakfast'], accommodation: '4-star hotel in Bangkok' },
      { day: 3, title: 'Floating Market & Transfer to Pattaya', description: 'Morning at the floating market, then drive to Pattaya\'s beaches.', activities: ['Damnoen Saduak Floating Market', 'Drive to Pattaya (2 hrs)', 'Pattaya Beach & Walking Street'], meals: ['Breakfast'], accommodation: 'Hotel in Pattaya' },
      { day: 4, title: 'Coral Island & Water Sports', description: 'Full day island hopping at Coral Island with beach time and water activities.', activities: ['Speedboat to Coral Island', 'Snorkeling & parasailing', 'Beach relaxation', 'Evening: Pattaya viewpoint'], meals: ['Breakfast', 'Lunch'], accommodation: 'Hotel in Pattaya' },
      { day: 5, title: 'Departure', description: 'Transfer back to Bangkok airport for your flight home.', activities: ['Breakfast & checkout', 'Last minute shopping', 'Transfer to Bangkok airport'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/bangkok-grand-palace.jpg',
      '/images/packages/bangkok-grand-palace.jpg',
      '/images/packages/bangkok-grand-palace.jpg',
    ],
    thumbnailImage: '/images/packages/bangkok-grand-palace.jpg',
    maxGroupSize: 20, difficulty: 'Easy', isActive: true, isFeatured: true,
    tags: ['international', 'thailand', 'beach', 'adventure'],
    pdfUrl: '/pdfs/thailand-5d4n.pdf', createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'essence-of-ladakh-4d3n',
    title: 'Essence of Ladakh Biking Expedition — 4D 3N',
    slug: 'essence-of-ladakh-4d3n',
    category: 'Adventure',
    duration: '4D 3N',
    price: 19999,
    location: 'Leh, Ladakh',
    description: 'A thrilling biking expedition through Ladakh covering Khardung La Pass (18,380 ft), monasteries, and magnetic hill.',
    longDescription: 'Ride through the roof of the world on Royal Enfield Himalayan 411cc bikes. Cross Khardung La — one of the world\'s highest motorable passes at 18,380 ft. Visit ancient monasteries perched on cliffsides, experience the mysterious Magnetic Hill, and witness the confluence of the Indus and Zanskar rivers at Sangam. Premium hotels with South Indian food ensure comfort after each thrilling day on the road.',
    highlights: ['Khardung La Pass (18,380 ft)', 'Sangam View Point & Magnetic Hill', 'Hemis & Thikshey Monastery', 'Premium hotel with South Indian food'],
    inclusions: ['Premium hotel (3 nights)', 'All breakfasts & dinners', 'Himalayan 411cc bikes with unlimited fuel', 'Riding jackets, helmets & gloves', 'Medical kits & oxygen cylinders', 'Travel insurance', 'Marshal & backup vehicles', 'Campfire evening'],
    exclusions: ['Flight tickets to Leh', 'Lunch', 'Personal expenses', 'Fuel damage charges', 'Anything not in inclusions'],
    itinerary: [
      { day: 1, title: 'Arrival in Leh & Acclimatization', description: 'Fly into Leh and spend the day acclimatizing to the altitude (11,500 ft). Light walks only.', activities: ['Airport pickup', 'Hotel check-in', 'Rest & acclimatize', 'Leh market evening walk', 'Bike allocation & briefing'], meals: ['Dinner'], accommodation: 'Premium hotel in Leh' },
      { day: 2, title: 'Leh Local Sightseeing by Bike', description: 'First day on the bikes exploring Leh\'s iconic landmarks and monasteries.', activities: ['Ride to Shanti Stupa', 'Hemis Monastery visit', 'Thikshey Monastery (Mini Potala)', 'Sangam Point (Indus-Zanskar confluence)', 'Magnetic Hill experience'], meals: ['Breakfast', 'Dinner'], accommodation: 'Premium hotel in Leh' },
      { day: 3, title: 'Khardung La Pass Expedition', description: 'The ultimate ride — conquer Khardung La at 18,380 ft, one of the world\'s highest motorable roads.', activities: ['Early morning departure', 'Ride to Khardung La (18,380 ft)', 'Photo stop at summit', 'Descend to South Pullu', 'Campfire celebration evening'], meals: ['Breakfast', 'Dinner'], accommodation: 'Premium hotel in Leh' },
      { day: 4, title: 'Departure', description: 'Breakfast and transfer to Leh airport with incredible memories.', activities: ['Breakfast & checkout', 'Last minute Leh market shopping', 'Airport transfer'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/ladakh-biking.jpg',
      '/images/packages/kerala-backwaters.jpg',
      '/images/packages/everest-nepal.jpg',
      '/images/packages/everest-nepal.jpg',
    ],
    thumbnailImage: '/images/packages/ladakh-biking.jpg',
    maxGroupSize: 15, difficulty: 'Challenging', isActive: true, isFeatured: true,
    tags: ['adventure', 'biking', 'ladakh'], pdfUrl: '/pdfs/essence-of-ladakh-4d3n.pdf',
    createdAt: new Date(), updatedAt: new Date(),
  },
  {
    id: 'andaman-couple-retreat-7d6n',
    title: 'Andaman & Nicobar Couple Retreat — 7D 6N',
    slug: 'andaman-couple-retreat-7d6n',
    category: 'Adventure',
    duration: '7D 6N',
    price: 35000,
    location: 'Port Blair, Havelock & Neil Island',
    description: 'A romantic island retreat covering Port Blair, Havelock, and Neil Island with pristine beaches, snorkeling, and water sports.',
    longDescription: 'Escape to India\'s tropical paradise with your partner. Watch history come alive at the Cellular Jail light and sound show, sink your toes into Asia\'s best beach at Radhanagar, snorkel through vibrant coral reefs at Elephant Beach, and discover Neil Island\'s natural rock bridge. Every sunset here is a masterpiece.',
    highlights: ['Radhanagar Beach — Asia\'s best beach', 'Cellular Jail Sound & Light Show', 'Elephant Beach water sports & snorkeling', 'Neil Island natural rock bridge'],
    inclusions: ['3-star hotels & resorts (6 nights)', 'All breakfasts', 'A/C vehicle transfers', 'All ferry & boat charges', 'Entry tickets & permits', 'Cellular Jail light & sound show tickets'],
    exclusions: ['Flight tickets', 'Lunch & dinner', 'Scuba diving (optional)', 'Jet ski & parasailing', 'Personal expenses', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrival in Port Blair', description: 'Arrive at Veer Savarkar Airport. Visit the historic Cellular Jail and witness the moving light and sound show.', activities: ['Airport pickup', 'Hotel check-in & rest', 'Cellular Jail visit', 'Light & Sound Show (evening)'], meals: [], accommodation: 'Hotel in Port Blair' },
      { day: 2, title: 'Ross Island & North Bay', description: 'Explore the ruins of British-era Ross Island and snorkel at North Bay.', activities: ['Ferry to Ross Island', 'Explore colonial ruins & deer park', 'North Bay coral viewing', 'Glass bottom boat ride', 'Snorkeling'], meals: ['Breakfast'], accommodation: 'Hotel in Port Blair' },
      { day: 3, title: 'Transfer to Havelock Island', description: 'Take the cruise to Havelock Island and visit the stunning Radhanagar Beach.', activities: ['Morning cruise to Havelock', 'Resort check-in', 'Radhanagar Beach sunset (Beach #7)'], meals: ['Breakfast'], accommodation: 'Resort in Havelock' },
      { day: 4, title: 'Elephant Beach & Water Sports', description: 'Full day of adventure at Elephant Beach with snorkeling and water sports.', activities: ['Speedboat to Elephant Beach', 'Snorkeling in crystal waters', 'Kayaking & jet ski (optional)', 'Relax on the beach'], meals: ['Breakfast'], accommodation: 'Resort in Havelock' },
      { day: 5, title: 'Transfer to Neil Island', description: 'Ferry to serene Neil Island — the vegetable bowl of Andaman.', activities: ['Ferry to Neil Island', 'Bharatpur Beach visit', 'Natural rock bridge (Howrah Bridge)', 'Laxmanpur Beach sunset'], meals: ['Breakfast'], accommodation: 'Hotel in Neil Island' },
      { day: 6, title: 'Neil Island & Return to Port Blair', description: 'Morning beach time, then ferry back to Port Blair for last-day shopping.', activities: ['Morning beach walk', 'Ferry to Port Blair', 'Sagarika Emporium shopping', 'Aberdeen Bazaar walk'], meals: ['Breakfast'], accommodation: 'Hotel in Port Blair' },
      { day: 7, title: 'Departure', description: 'Transfer to airport for your flight home.', activities: ['Breakfast & checkout', 'Airport transfer', 'Departure with memories'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/andaman-beach.jpg',
      '/images/packages/andaman-beach.jpg',
      '/images/packages/andaman-beach.jpg',
      '/images/packages/tropical-island.jpg',
    ],
    thumbnailImage: '/images/packages/andaman-beach.jpg',
    maxGroupSize: 10, difficulty: 'Easy', isActive: true, isFeatured: true,
    tags: ['island', 'andaman', 'couple', 'beach'], pdfUrl: '/pdfs/andaman-couple-retreat-7d6n.pdf',
    createdAt: new Date(), updatedAt: new Date(),
  },
  // Remaining adventure trips with standard template
  ...[
    { id: 'manali-4d3n', title: 'Manali Mountain Retreat — 4D 3N', dur: '4D 3N', price: 9999, loc: 'Manali, Himachal Pradesh', desc: 'A mountain getaway with snow-capped peaks, Solang Valley adventures, Old Manali charm, and Rohtang views.', hi: ['Solang Valley adventure sports', 'Old Manali exploration', 'Hadimba Temple visit', 'Rohtang Pass scenic views'], img: '/images/packages/manali-mountains.jpg', pdf: '/pdfs/manali-4d3n.pdf', diff: 'Easy' as const },
    { id: 'leh-ladakh-biking-9d8n', title: 'Leh-Ladakh Biking Retreat — 9D 8N', dur: '9D 8N', price: 35000, loc: 'Leh-Ladakh', desc: 'The ultimate 9-day Ladakh biking adventure — Manali-Leh highway, Pangong Lake, Nubra Valley.', hi: ['Manali-Leh highway ride', 'Pangong Lake camping', 'Nubra Valley & Diskit Monastery', 'Multiple passes above 17,000 ft'], img: '/images/packages/ladakh-biking.jpg', pdf: '/pdfs/leh-ladakh-biking-9d8n.pdf', diff: 'Challenging' as const },
    { id: 'kenya-simba-safari-5d4n', title: 'Kenya Simba Safari — 5D 4N', dur: '5D 4N', price: 95000, loc: 'Masai Mara, Kenya', desc: 'An African safari with Big Five game drives, Maasai village visits, and savanna sunsets.', hi: ['Big Five game drives', 'Maasai village cultural visit', 'Savanna sunrise & sunset', 'Safari lodge stay'], img: '/images/packages/kenya-safari.jpg', pdf: '/pdfs/kenya-simba-safari-5d4n.jpg', diff: 'Easy' as const },
    { id: 'kenya-5d4n', title: 'Kenya Explorer — 5D 4N', dur: '5D 4N', price: 85000, loc: 'Nairobi & Masai Mara, Kenya', desc: 'Explore Kenya\'s wildlife and culture with game drives and Maasai cultural interactions.', hi: ['Masai Mara game drives', 'Nairobi National Park', 'Giraffe Centre visit', 'Cultural experiences'], img: '/images/packages/kenya-safari.jpg', pdf: '/pdfs/kenya-5d4n.jpg', diff: 'Easy' as const },
    { id: 'lakshadweep-4d3n', title: 'Lakshadweep Island Escape — 4D 3N', dur: '4D 3N', price: 25000, loc: 'Lakshadweep Islands', desc: 'India\'s coral paradise with crystal clear lagoons, white sand beaches, and underwater marine life.', hi: ['Crystal clear lagoon swims', 'Coral reef snorkeling', 'White sand beach walks', 'Glass bottom boat rides'], img: '/images/packages/andaman-beach.jpg', pdf: '/pdfs/lakshadweep-4d3n.pdf', diff: 'Easy' as const },
    { id: 'kolukkumalai-mankulam-munnar-5d4n', title: 'Kolukkumalai - Mankulam - Munnar — 5D 4N', dur: '5D 4N', price: 12999, loc: 'Munnar Region, Kerala', desc: 'Adventure through Kerala\'s highest tea plantations, tribal villages, and misty mountain trails.', hi: ['World\'s highest tea plantation', 'Mankulam tribal village', 'Munnar tea gardens & waterfalls', 'Jeep ride through cloud forests'], img: '/images/packages/munnar-tea.jpg', pdf: '/pdfs/kolukkumalai-mankulam-munnar-5d4n.pdf', diff: 'Moderate' as const },
    { id: 'kanthalloor-kolukkumalai-3d2n', title: 'Kanthalloor & Kolukkumalai — 3D 2N', dur: '3D 2N', price: 7999, loc: 'Kanthalloor & Kolukkumalai, Kerala', desc: 'Explore Kerala\'s fruit village and the world\'s highest tea plantation.', hi: ['Kanthalloor fruit orchards', 'Kolukkumalai sunrise trek', 'World\'s highest tea plantation', 'Mountain camping'], img: '/images/packages/munnar-tea.jpg', pdf: '/pdfs/kanthalloor-kolukkumalai-3d2n.pdf', diff: 'Moderate' as const },
    { id: 'kanthalloor-mankulam-3d2n', title: 'Kanthalloor & Mankulam — 3D 2N', dur: '3D 2N', price: 7999, loc: 'Kanthalloor & Mankulam, Kerala', desc: 'A tribal village adventure combining orchards with indigenous community experiences.', hi: ['Tribal village immersion', 'Kanthalloor fruit gardens', 'Forest trekking', 'Local cuisine experience'], img: '/images/packages/munnar-tea.jpg', pdf: '/pdfs/kanthalloor-mankulam-3d2n.pdf', diff: 'Moderate' as const },
  ].map(t => ({
    id: t.id, title: t.title, slug: t.id, category: 'Adventure' as const, duration: t.dur, price: t.price, location: t.loc,
    description: t.desc,
    longDescription: `${t.desc} Every detail is personally curated by GP Travels founder Rajeev Gnanavel to ensure authentic, memorable experiences. Contact us for the full detailed itinerary PDF and group pricing.`,
    highlights: t.hi,
    inclusions: ['Hotel/resort accommodation', 'Breakfast daily', 'AC transport/transfers', 'Experienced local guide', 'All entry tickets & permits', 'First aid support'],
    exclusions: ['Flight/train tickets', 'Lunch & dinner (unless specified)', 'Personal expenses', 'Optional activities', 'Travel insurance', 'Tips & gratuities'],
    itinerary: [
      { day: 1, title: 'Arrival & Exploration', description: 'Arrive at the destination, check-in, and begin exploring the local area.', activities: ['Airport/station pickup', 'Hotel check-in', 'Local area exploration', 'Evening briefing'], meals: ['Dinner'], accommodation: 'Hotel/resort' },
      { day: 2, title: 'Main Adventure Day', description: 'The highlight of the trip — full day of the core adventure experience.', activities: ['Core adventure activity', 'Scenic exploration', 'Cultural interactions', 'Photography stops'], meals: ['Breakfast', 'Lunch'], accommodation: 'Hotel/resort' },
      { day: 3, title: 'Exploration & Departure', description: 'Final explorations and transfer back.', activities: ['Morning activity', 'Souvenir shopping', 'Transfer to airport/station'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [t.img, '/images/packages/manali-mountains.jpg', '/images/packages/beach-sunset.jpg'],
    thumbnailImage: t.img, maxGroupSize: 15, difficulty: t.diff, isActive: true, isFeatured: false,
    tags: ['adventure'], pdfUrl: t.pdf, createdAt: new Date(), updatedAt: new Date(),
  } as TravelPackage)),

  // ─── WEEKEND CAMPINGS ────────────────────────────────────
  ...[
    { id: 'kanthalloor-2d1n', title: 'Kanthalloor Adventure Camping — 2D 1N', price: 3999, loc: 'Kanthalloor, Kerala', desc: 'Weekend camping in Kerala\'s fruit village with orchard walks, campfire nights, and mountain views.', hi: ['Campfire under the stars', 'Fruit orchard walks', 'Mountain sunrise views', 'Local village experience'], pdf: '/pdfs/kanthalloor-2d1n.pdf' },
    { id: 'nelliyampathy-2d1n', title: 'Nelliyampathy Hills Camping — 2D 1N', price: 3999, loc: 'Nelliyampathy, Kerala', desc: 'Camp in the misty Nelliyampathy hills with tea garden treks, viewpoint hikes, and bonfire nights.', hi: ['Misty hill camping', 'Tea garden trek', 'Seetharkundu Viewpoint', 'Bonfire & BBQ night'], pdf: '/pdfs/nelliyampathy-2d1n.pdf' },
    { id: 'kolukkumalai-2d1n', title: 'Kolukkumalai Sunrise Camping — 2D 1N', price: 4499, loc: 'Kolukkumalai, Kerala', desc: 'Camp at the world\'s highest tea plantation and witness a breathtaking sunrise above the clouds.', hi: ['Sunrise above the clouds', 'World\'s highest tea plantation', 'Jeep ride through tea estates', 'Campfire at high altitude'], pdf: '/pdfs/kolukkumalai-2d1n.pdf' },
  ].map(t => ({
    id: t.id, title: t.title, slug: t.id, category: 'Weekend' as const, duration: '2D 1N', price: t.price, location: t.loc,
    description: t.desc,
    longDescription: `${t.desc} Perfect for a quick weekend escape from the city. Includes camping equipment, campfire setup, guided nature walks, and authentic local meals prepared fresh at the campsite.`,
    highlights: t.hi,
    inclusions: ['Tent accommodation', 'Campfire & BBQ setup', 'Dinner & breakfast', 'Guided nature walk/trek', 'Transport from pickup point', 'First aid kit'],
    exclusions: ['Transport to pickup point', 'Personal gear', 'Snacks & beverages', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrival & Camp Setup', description: 'Arrive at the campsite, settle in, explore the area, and enjoy an evening campfire.', activities: ['Pickup point transfer', 'Campsite check-in', 'Guided nature walk / short trek', 'Campfire with music & stories', 'BBQ dinner under the stars'], meals: ['Dinner'], accommodation: 'Tent camping' },
      { day: 2, title: 'Sunrise, Breakfast & Departure', description: 'Wake up early for a stunning sunrise, enjoy breakfast, and head back refreshed.', activities: ['Early morning sunrise point trek', 'Photography session', 'Breakfast at campsite', 'Pack up & departure'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/camping-bonfire.jpg',
      '/images/packages/tent-stars.jpg',
      '/images/packages/munnar-tea.jpg',
    ],
    thumbnailImage: '/images/packages/camping-bonfire.jpg',
    maxGroupSize: 15, difficulty: 'Easy' as const, isActive: true, isFeatured: false,
    tags: ['camping', 'weekend', 'kerala'], pdfUrl: t.pdf, createdAt: new Date(), updatedAt: new Date(),
  } as TravelPackage)),

  // ─── AGROTOURISM ─────────────────────────────────────────
  ...[
    { id: 'kolukkumalai-mankulam-munnar-5d4n-agro', title: 'Munnar Agrotourism Trail — 5D 4N', price: 12999, loc: 'Munnar Region, Kerala', desc: 'Explore Kerala\'s tea country — visit working plantations, tribal farms, and spice gardens.', hi: ['Tea plantation factory tour', 'Tribal organic farming', 'Spice garden walk', 'Fresh farm-to-table meals'], pdf: '/pdfs/kolukkumalai-mankulam-munnar-5d4n.pdf' },
    { id: 'kanthalloor-kolukkumalai-3d2n-agro', title: 'Kanthalloor Farm & Tea Experience — 3D 2N', price: 7999, loc: 'Kanthalloor, Kerala', desc: 'Stay in Kerala\'s fruit village, pick fresh produce, and visit the world\'s highest tea plantation.', hi: ['Fruit picking experience', 'Tea plantation sunrise trek', 'Farm-to-table cooking', 'Village homestay'], pdf: '/pdfs/kanthalloor-kolukkumalai-3d2n.pdf' },
    { id: 'kanthalloor-mankulam-3d2n-agro', title: 'Tribal Agro Village Experience — 3D 2N', price: 7999, loc: 'Kanthalloor & Mankulam, Kerala', desc: 'Live with tribal farming communities, learn indigenous agriculture, and cook traditional meals.', hi: ['Tribal community stay', 'Indigenous farming workshop', 'Traditional cooking class', 'Forest produce foraging'], pdf: '/pdfs/kanthalloor-mankulam-3d2n.pdf' },
  ].map(t => ({
    id: t.id, title: t.title, slug: t.id, category: 'Agrotourism' as const,
    duration: t.id.includes('5d4n') ? '5D 4N' : '3D 2N',
    price: t.price, location: t.loc, description: t.desc,
    longDescription: `${t.desc} GP Travels pioneers agrotourism in South India — connecting city dwellers with the land, farmers, and traditions that sustain us. Every stay supports local farming communities directly.`,
    highlights: t.hi,
    inclusions: ['Homestay/farmstay accommodation', 'All meals (farm-to-table)', 'Farming activities & workshops', 'Local guide', 'Transport from pickup point'],
    exclusions: ['Transport to pickup point', 'Personal expenses', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrival at the Farm', description: 'Arrive at the farmstay, meet your host family, and get a tour of the farm and surroundings.', activities: ['Pickup & transfer to farm', 'Farm tour & orientation', 'Hands-on farming activity', 'Traditional dinner with host family'], meals: ['Dinner'], accommodation: 'Farmstay/Homestay' },
      { day: 2, title: 'Farm Life & Village Walk', description: 'Full day immersed in farm life — harvesting, cooking with fresh produce, and exploring the village.', activities: ['Morning harvest activity', 'Farm-to-table cooking class', 'Village walk & local market', 'Evening bonfire & stories'], meals: ['Breakfast', 'Lunch', 'Dinner'], accommodation: 'Farmstay/Homestay' },
      { day: 3, title: 'Sunrise & Departure', description: 'Final morning with sunrise views and breakfast before heading back.', activities: ['Sunrise viewpoint walk', 'Breakfast with family', 'Departure with fresh produce gift'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/munnar-tea.jpg',
      '/images/packages/farm-green.jpg',
      '/images/packages/kerala-backwaters.jpg',
    ],
    thumbnailImage: '/images/packages/munnar-tea.jpg',
    maxGroupSize: 12, difficulty: 'Easy' as const, isActive: true, isFeatured: false,
    tags: ['agrotourism', 'kerala', 'farming'], pdfUrl: t.pdf, createdAt: new Date(), updatedAt: new Date(),
  } as TravelPackage)),

  // ─── SPIRITUAL ───────────────────────────────────────────
  {
    id: 'vaishnodevi-kashmir-6d5n',
    title: 'Vaishno Devi + Kashmir — 6D 5N',
    slug: 'vaishnodevi-kashmir-6d5n',
    category: 'Spiritual',
    duration: '6D 5N',
    price: 14999,
    location: 'Jammu, Pahalgam, Srinagar & Gulmarg',
    description: 'Spiritual-cum-scenic trip combining Vaishno Devi darshan with Kashmir\'s iconic valleys, gardens, and Dal Lake houseboat.',
    longDescription: 'Begin with the sacred Vaishno Devi pilgrimage in Jammu, then journey into the paradise of Kashmir. Explore the flower-filled Betaab Valley and Aru Valley in Pahalgam, take the Gulmarg Gondola for snow-capped panoramas, wander through Mughal Gardens in Srinagar, and end with a magical sunset Shikara ride on Dal Lake followed by an overnight houseboat stay.',
    highlights: ['Vaishno Devi darshan', 'Betaab Valley & Aru Valley', 'Gulmarg Gondola ride', 'Dal Lake Shikara ride & houseboat stay'],
    inclusions: ['3-star accommodation (5 nights)', 'One night houseboat on Dal Lake', 'Breakfast & dinner daily', 'Airport transfers', 'AC vehicle for all sightseeing', '1-hour Shikara ride', 'Welcome drinks'],
    exclusions: ['Flight tickets', 'Vaishno Devi helicopter (optional)', 'Gulmarg Gondola ticket', 'Lunch', 'Pony/palki for Vaishno Devi', 'Personal expenses', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrival in Jammu & Vaishno Devi', description: 'Arrive at Jammu, transfer to Katra. Begin the Vaishno Devi trek in the evening.', activities: ['Jammu airport pickup', 'Transfer to Katra (1.5 hrs)', 'Evening: Begin Vaishno Devi trek/helicopter'], meals: ['Dinner'], accommodation: 'Hotel in Katra' },
      { day: 2, title: 'Vaishno Devi Darshan & Pahalgam', description: 'Complete darshan, descend, and drive to the beautiful valley town of Pahalgam.', activities: ['Vaishno Devi darshan', 'Descend to Katra', 'Drive to Pahalgam (5 hrs)', 'Check-in & rest'], meals: ['Breakfast', 'Dinner'], accommodation: 'Hotel in Pahalgam' },
      { day: 3, title: 'Pahalgam Valley Exploration', description: 'Full day exploring the stunning valleys around Pahalgam — Bollywood\'s favourite backdrop.', activities: ['Betaab Valley visit', 'Aru Valley exploration', 'Chandanwari (optional)', 'Lidder River walk'], meals: ['Breakfast', 'Dinner'], accommodation: 'Hotel in Pahalgam' },
      { day: 4, title: 'Gulmarg Sightseeing', description: 'Drive to Gulmarg — the meadow of flowers. Optional Gondola ride for breathtaking views.', activities: ['Drive to Gulmarg (4 hrs)', 'Gondola Phase 1 & 2 (optional)', 'Snow activities (seasonal)', 'Drive to Srinagar'], meals: ['Breakfast', 'Dinner'], accommodation: 'Hotel in Srinagar' },
      { day: 5, title: 'Srinagar & Dal Lake', description: 'Explore Mughal Gardens and end with a magical Shikara ride and houseboat stay.', activities: ['Nishat Bagh & Shalimar Garden', 'Shankaracharya Temple', 'Hazratbal Shrine', 'Sunset Shikara ride on Dal Lake'], meals: ['Breakfast', 'Dinner'], accommodation: 'Houseboat on Dal Lake' },
      { day: 6, title: 'Departure', description: 'Breakfast on the houseboat and transfer to Srinagar airport.', activities: ['Houseboat breakfast', 'Local market shopping', 'Airport transfer', 'Departure'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/kashmir-dal-lake.jpg',
      '/images/packages/kerala-backwaters.jpg',
      '/images/packages/everest-nepal.jpg',
      '/images/packages/munnar-tea.jpg',
    ],
    thumbnailImage: '/images/packages/kashmir-dal-lake.jpg',
    maxGroupSize: 20, difficulty: 'Moderate', isActive: true, isFeatured: true,
    tags: ['spiritual', 'kashmir', 'vaishno-devi'], pdfUrl: '/pdfs/vaishnodevi-kashmir-6d5n.pdf',
    createdAt: new Date(), updatedAt: new Date(),
  },
  ...[
    { id: 'odisha-spiritual-nature-4d3n', title: 'Odisha Spiritual + Nature Retreat — 4D 3N', dur: '4D 3N', price: 11999, loc: 'Bhubaneswar, Puri & Konark, Odisha', desc: 'Spiritual retreat covering Jagannath Temple, UNESCO Konark Sun Temple, and Chilika Lake dolphins.', hi: ['Jagannath Temple — one of four dhams', 'Konark Sun Temple (UNESCO)', 'Chilika Lake Irrawaddy Dolphins', 'Lingaraj Temple & ancient caves'], pdf: '/pdfs/odisha-spiritual-nature-4d3n.pdf' },
    { id: 'ram-krishna-yatra-6d5n', title: 'Ram-Krishna Yatra — 6D 5N', dur: '6D 5N', price: 15999, loc: 'Delhi, Vrindavan, Agra & Ayodhya', desc: 'Spiritual pilgrimage covering Vrindavan, Taj Mahal, and Ram Janmabhoomi in Ayodhya.', hi: ['Vrindavan temples — Banke Bihari, ISKCON', 'Taj Mahal & Agra Fort', 'Ram Janmabhoomi & Hanuman Garhi', 'Delhi — India Gate, Qutub Minar'], pdf: '/pdfs/ram-krishna-yatra-6d5n.pdf' },
    { id: 'puri-jagannath-odisha-4d3n', title: 'Puri Jagannath Odisha Retreat — 4D 3N', dur: '4D 3N', price: 10999, loc: 'Bhubaneswar, Puri & Chilika, Odisha', desc: 'Focused Odisha retreat centered on the 12th century Jagannath Temple with Chilika Lake dolphins.', hi: ['Jagannath Temple — 12th century', 'Konark Sun Temple', 'Chilika Lake dolphin spotting', 'Nandankanan Zoo & temples'], pdf: '/pdfs/puri-jagannath-odisha-4d3n.pdf' },
    { id: 'arupadai-veedu-4d3n', title: 'Arupadai Veedu — Six Abodes of Murugan — 4D 3N', dur: '4D 3N', price: 8999, loc: 'Tamil Nadu', desc: 'Sacred pilgrimage to all six abodes of Lord Murugan across Tamil Nadu.', hi: ['Palani Dhandayuthapani Temple', 'Tiruchendur seaside temple', 'Swamimalai Swaminatha Swamy', 'Thiruthani, Pazhamudircholai & Thirupparankundram'], pdf: '/pdfs/arupadai-veedu-4d3n.pdf' },
  ].map(t => ({
    id: t.id, title: t.title, slug: t.id, category: 'Spiritual' as const, duration: t.dur, price: t.price, location: t.loc,
    description: t.desc,
    longDescription: `${t.desc} GP Travels ensures a comfortable and deeply meaningful pilgrimage experience with knowledgeable guides, comfortable stays, and all temple visit arrangements handled for you.`,
    highlights: t.hi,
    inclusions: ['Hotel accommodation', 'Breakfast & dinner', 'AC vehicle for all transfers', 'Local temple guide', 'All darshan arrangements', 'VIP entry where available'],
    exclusions: ['Flight/train tickets', 'Lunch', 'Special pooja charges', 'Personal expenses', 'Camera fees at temples', 'Travel insurance'],
    itinerary: [
      { day: 1, title: 'Arrival & First Temple', description: 'Arrive at the destination, check-in, and visit the first major temple.', activities: ['Airport/station pickup', 'Hotel check-in', 'First temple visit & darshan', 'Evening aarti experience'], meals: ['Dinner'], accommodation: 'Hotel' },
      { day: 2, title: 'Temple Circuit', description: 'Full day visiting the main temples and spiritual sites on the circuit.', activities: ['Early morning temple darshan', 'Heritage temple visits', 'Guided spiritual commentary', 'Evening meditation/aarti'], meals: ['Breakfast', 'Dinner'], accommodation: 'Hotel' },
      { day: 3, title: 'Nature & Culture', description: 'Combine spiritual visits with natural wonders and cultural experiences.', activities: ['Morning temple visit', 'Nature/lake/heritage site', 'Local crafts & market', 'Farewell dinner'], meals: ['Breakfast', 'Dinner'], accommodation: 'Hotel' },
      { day: 4, title: 'Final Darshan & Departure', description: 'Last temple visit and departure with divine blessings.', activities: ['Early morning darshan', 'Prasad shopping', 'Transfer to airport/station'], meals: ['Breakfast'], accommodation: '' },
    ],
    images: [
      '/images/packages/india-temple.jpg',
      '/images/packages/kashmir-mountains.jpg',
      '/images/packages/kashmir-dal-lake.jpg',
    ],
    thumbnailImage: '/images/packages/india-temple.jpg',
    maxGroupSize: 20, difficulty: 'Easy' as const, isActive: true, isFeatured: false,
    tags: ['spiritual', 'pilgrimage'], pdfUrl: t.pdf, createdAt: new Date(), updatedAt: new Date(),
  } as TravelPackage)),
];
